package za.co.tinyiko.transactionaggregation.merchant.domain;

import java.time.Clock;
import java.time.Instant;
import java.util.Objects;

/**
 * The Merchant aggregate (SAD 27.4) — a normalised merchant identity.
 *
 * <p>Immutable after creation: neither SAD nor TDS documents a status, lifecycle, or
 * update-name capability for Merchant, unlike {@code Customer}. There are no behaviour
 * methods here, deliberately — nothing to transition.
 *
 * <p>Optimistic-locking version is not carried here, same convention as {@code Customer} —
 * held only by the JPA entity in {@code merchant.persistence}, even though nothing currently
 * mutates a persisted Merchant. SAD 27.4 lists the field explicitly, so the persistence
 * schema follows it regardless of current usage.
 */
public final class Merchant {

	private static final int MAX_NAME_LENGTH = 255;

	private final MerchantId id;
	private final String normalisedName;
	private final String displayName;
	private final Instant createdAt;
	private final Instant updatedAt;

	private Merchant(MerchantId id, String normalisedName, String displayName, Instant createdAt, Instant updatedAt) {
		this.id = id;
		this.normalisedName = normalisedName;
		this.displayName = displayName;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	/**
	 * Registers a new merchant. {@code id} is generated by the caller (see
	 * {@link MerchantId#generate()}), not by this method. {@code normalisedName} and
	 * {@code displayName} are expected to already be derived by the caller (see
	 * {@link MerchantNormaliser}) — this factory validates them, it does not derive them.
	 */
	public static Merchant register(MerchantId id, String normalisedName, String displayName, Clock clock) {
		Objects.requireNonNull(id, "id must not be null");
		Objects.requireNonNull(clock, "clock must not be null");
		String validatedNormalisedName = requireInBounds(normalisedName, "normalisedName");
		String validatedDisplayName = requireInBounds(displayName, "displayName");

		Instant now = Instant.now(clock);
		return new Merchant(id, validatedNormalisedName, validatedDisplayName, now, now);
	}

	/**
	 * Rebuilds a merchant from already-trusted persisted data. Does not re-run the invariant
	 * checks {@link #register} performs.
	 */
	public static Merchant reconstitute(
			MerchantId id, String normalisedName, String displayName, Instant createdAt, Instant updatedAt) {
		Objects.requireNonNull(id, "id must not be null");
		Objects.requireNonNull(normalisedName, "normalisedName must not be null");
		Objects.requireNonNull(displayName, "displayName must not be null");
		Objects.requireNonNull(createdAt, "createdAt must not be null");
		Objects.requireNonNull(updatedAt, "updatedAt must not be null");
		return new Merchant(id, normalisedName, displayName, createdAt, updatedAt);
	}

	private static String requireInBounds(String value, String fieldName) {
		Objects.requireNonNull(value, fieldName + " must not be null");
		if (value.isBlank()) {
			throw new IllegalArgumentException(fieldName + " must not be blank");
		}
		if (value.length() > MAX_NAME_LENGTH) {
			throw new IllegalArgumentException(fieldName + " must not exceed " + MAX_NAME_LENGTH + " characters");
		}
		return value;
	}

	public MerchantId id() {
		return id;
	}

	public String normalisedName() {
		return normalisedName;
	}

	public String displayName() {
		return displayName;
	}

	public Instant createdAt() {
		return createdAt;
	}

	public Instant updatedAt() {
		return updatedAt;
	}

	@Override
	public boolean equals(Object other) {
		if (this == other) {
			return true;
		}
		if (!(other instanceof Merchant otherMerchant)) {
			return false;
		}
		return id.equals(otherMerchant.id);
	}

	@Override
	public int hashCode() {
		return id.hashCode();
	}

	@Override
	public String toString() {
		return "Merchant{id=%s, normalisedName=%s}".formatted(id, normalisedName);
	}

}
