package za.co.tinyiko.transactionaggregation.customer.domain;

import java.time.Clock;
import java.time.Instant;
import java.util.Objects;
import java.util.regex.Pattern;

/**
 * The Customer aggregate (SAD 27.1) — the owner of financial transactions.
 *
 * <p>A plain, mutable class rather than a record: {@code status} and {@code updatedAt}
 * genuinely change over the aggregate's life; every other field is set once at construction.
 * No field-level setters exist for the immutable fields — nothing in the SAD/TDS documents an
 * "update name/email" use case, so none is invented here.
 *
 * <p>Optimistic-locking version is deliberately not carried here — it is a persistence
 * concern, held only by the JPA entity in {@code customer.persistence}.
 */
public final class Customer {

	private static final int MAX_REFERENCE_LENGTH = 100;
	private static final int MAX_NAME_LENGTH = 100;
	private static final int MAX_EMAIL_LENGTH = 254;
	private static final Pattern EMAIL_PATTERN = Pattern.compile("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$");

	private final CustomerId id;
	private final String externalReference;
	private final String firstName;
	private final String lastName;
	private final String emailAddress;
	private CustomerStatus status;
	private final Instant createdAt;
	private Instant updatedAt;

	private Customer(
			CustomerId id,
			String externalReference,
			String firstName,
			String lastName,
			String emailAddress,
			CustomerStatus status,
			Instant createdAt,
			Instant updatedAt
	) {
		this.id = id;
		this.externalReference = externalReference;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailAddress = emailAddress;
		this.status = status;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	/**
	 * Registers a new customer. {@code id} is generated by the caller (see
	 * {@link CustomerId#generate()}), not by this method — the aggregate does not decide how
	 * its own identity is produced.
	 */
	public static Customer register(
			CustomerId id,
			String externalReference,
			String firstName,
			String lastName,
			String emailAddress,
			Clock clock
	) {
		Objects.requireNonNull(id, "id must not be null");
		Objects.requireNonNull(clock, "clock must not be null");
		String validatedReference = requireInBounds(externalReference, "externalReference", MAX_REFERENCE_LENGTH);
		String validatedFirstName = requireInBounds(firstName, "firstName", MAX_NAME_LENGTH);
		String validatedLastName = requireInBounds(lastName, "lastName", MAX_NAME_LENGTH);
		String validatedEmail = validateEmail(emailAddress);

		Instant now = Instant.now(clock);
		return new Customer(id, validatedReference, validatedFirstName, validatedLastName, validatedEmail,
				CustomerStatus.ACTIVE, now, now);
	}

	/**
	 * Rebuilds a customer from already-trusted persisted data. Does not re-run the invariant
	 * checks {@link #register} performs — that data was valid when it was written.
	 */
	public static Customer reconstitute(
			CustomerId id,
			String externalReference,
			String firstName,
			String lastName,
			String emailAddress,
			CustomerStatus status,
			Instant createdAt,
			Instant updatedAt
	) {
		Objects.requireNonNull(id, "id must not be null");
		Objects.requireNonNull(externalReference, "externalReference must not be null");
		Objects.requireNonNull(firstName, "firstName must not be null");
		Objects.requireNonNull(lastName, "lastName must not be null");
		Objects.requireNonNull(status, "status must not be null");
		Objects.requireNonNull(createdAt, "createdAt must not be null");
		Objects.requireNonNull(updatedAt, "updatedAt must not be null");
		return new Customer(id, externalReference, firstName, lastName, emailAddress, status, createdAt, updatedAt);
	}

	public void activate(Clock clock) {
		transitionTo(CustomerStatus.ACTIVE, clock);
	}

	public void suspend(Clock clock) {
		transitionTo(CustomerStatus.SUSPENDED, clock);
	}

	public void deactivate(Clock clock) {
		transitionTo(CustomerStatus.INACTIVE, clock);
	}

	private void transitionTo(CustomerStatus newStatus, Clock clock) {
		Objects.requireNonNull(newStatus, "newStatus must not be null");
		Objects.requireNonNull(clock, "clock must not be null");
		this.status = newStatus;
		this.updatedAt = Instant.now(clock);
	}

	private static String requireInBounds(String value, String fieldName, int maxLength) {
		Objects.requireNonNull(value, fieldName + " must not be null");
		if (value.isBlank()) {
			throw new IllegalArgumentException(fieldName + " must not be blank");
		}
		if (value.length() > maxLength) {
			throw new IllegalArgumentException(fieldName + " must not exceed " + maxLength + " characters");
		}
		return value;
	}

	private static String validateEmail(String emailAddress) {
		if (emailAddress == null) {
			return null;
		}
		if (emailAddress.length() > MAX_EMAIL_LENGTH) {
			throw new IllegalArgumentException("emailAddress must not exceed " + MAX_EMAIL_LENGTH + " characters");
		}
		if (!EMAIL_PATTERN.matcher(emailAddress).matches()) {
			throw new IllegalArgumentException("emailAddress must be a valid email address");
		}
		return emailAddress;
	}

	public CustomerId id() {
		return id;
	}

	public String externalReference() {
		return externalReference;
	}

	public String firstName() {
		return firstName;
	}

	public String lastName() {
		return lastName;
	}

	public String emailAddress() {
		return emailAddress;
	}

	public CustomerStatus status() {
		return status;
	}

	public Instant createdAt() {
		return createdAt;
	}

	public Instant updatedAt() {
		return updatedAt;
	}

	@Override
	public boolean equals(Object other) {
		if (this == other) {
			return true;
		}
		if (!(other instanceof Customer otherCustomer)) {
			return false;
		}
		return id.equals(otherCustomer.id);
	}

	@Override
	public int hashCode() {
		return id.hashCode();
	}

	@Override
	public String toString() {
		return "Customer{id=%s, externalReference=%s, status=%s}".formatted(id, externalReference, status);
	}

}
